name: Analyse SonarQube - Java (javac)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Configurer Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # adapte à ta version

      - name: Compiler le projet avec javac
        run: |
          mkdir -p bin
          javac -d bin $(find src -name "*.java")

      - name: Lancer l’analyse SonarQube
        uses: SonarSource/sonarqube-scan-action@v1.0.0
        with:
          host-url: ${{ secrets.SONAR_HOST_URL }}
          login: ${{ secrets.SONAR_TOKEN }}
